### ISSUE TITLE
Missing CC name for BU3D

### ISSUE THREAD

**Issue by fabiovinci** [inspire-eu-validation/INSPIRE-Validator-UI#10]
The name of the Conformance class "_Conformance Class 'INSPIRE GML application schemas (For BU3D)'_" is missing in the "Test suites" list. The error is present in both instances.

![image](https://user-images.githubusercontent.com/22212406/158133045-b0e8611a-f03c-4247-85c9-6247b5e8093e.png)

Same error in the summary page of the "Re-run":

![image](https://user-images.githubusercontent.com/22212406/158133605-ef56ffd4-eb85-4abf-b32d-e9ff5b0276af.png)

**Comment by fabianospinelli** [comment]
Description of the Conformance Class "Conformance Class 'INSPIRE GML application schemas (For BU3D)'" added in the branch "issues_15june"
