### ISSUE TITLE
Fix on label in Test Selection page and in Test rerun

### ISSUE THREAD

**Issue by veronicamonaco** [inspire-eu-validation/INSPIRE-Validator-UI#127]
Fix in the test selection page on label: 
'Provide a label for your test report 
(optional) Your test report will appear with the label below; edit the text if you wish to change it.' .
The bug is present on Firefox browser. (The same bug is present in the Test rerun page on the same label)
![image](https://github.com/user-attachments/assets/59d08b39-5e4a-4d49-bafd-2db43f3e0ccd)

**Comment by veronicamonaco** [comment]
Related to this issue, today we discovered another similar behavior (always present only in Firefox browser):
![image](https://github.com/user-attachments/assets/1909a69e-a9e4-483f-955d-0f874021e9f3)

**Comment by DanielMartinPerezdeLeon** [comment]
The change is uploaded to staging and seems to fix it.

Ready to merge.

Thank you!
