### ISSUE TITLE
Typo for AD data theme

### ISSUE THREAD

**Issue by fabiovinci** [inspire-eu-validation/INSPIRE-Validator-UI#13]
There is a typo in the "Advanced options" menu of the AD data theme, the name should be "Addresse**s**" instead of "Addresse**d**".

![image](https://user-images.githubusercontent.com/22212406/161109221-90acfc6b-8e81-47d9-926f-3b1920c38bfb.png)

The same error is present in the test report name.

![image](https://user-images.githubusercontent.com/22212406/161109945-bdbeea37-50f4-4539-b1b4-56121cbbef91.png)

The typo is present in both instances.

**Comment by fabianospinelli** [comment]
Label corrected (updated in branch "issues_15june"
