### ISSUE TITLE
Validating OGC API Features throws "Uncaught TypeError: Cannot read properties of undefined (reading 'testRuns')"

### ISSUE THREAD

**Issue by rkettelerij** [inspire-eu-validation/INSPIRE-Validator-UI#130]
The following Javascript error occurs when I try to validate an OGC API Features:

```
{error: 'The Object or dependent Objects could not be found…-465d-3162-ac1a-badef588dc76" could not be found!', timestamp: '1732260764878', url: 'http://localhost:8080/validator/v2/TestRuns', id: 'l.object.with.eid.not.found', stacktrace: Array(72)}
controller.js:6766 Uncaught TypeError: Cannot read properties of undefined (reading 'testRuns')
```

This prevents the test from starting (cursor just keeps spinning).

Screenshot:
<img width="1111" alt="Screenshot 2024-11-22 at 08 31 43" src="https://github.com/user-attachments/assets/547f14d3-17df-48f9-9305-58ef06385677">

**Comment by fabiovinci** [comment]
Dear @rkettelerij,

The issue has been resolved. Could you please try it and let us know if it works?
Thanks

**Comment by rkettelerij** [comment]
Thanks @fabiovinci this now works as expected.
