### ISSUE TITLE
Wrong CC for some US application schemas

### ISSUE THREAD

**Issue by fabiovinci** [inspire-eu-validation/INSPIRE-Validator-UI#22]
It has been detected that Conformance Class '_Application schema, Common Utility Network_'  shouldn't be displayed for the two US application schemas “_Administrative And Social Governmental Services_” and “_Environmental Management Facilities_” as it is not inherited by the relevant Conformance Classes.

Thus, it is proposed to remove this CC from being displayed for these Applications Schemas.

Regarding the dependencies between CCs, they are all valid apart from the one between the "Conformance Class 'Application schema, Administrative And Social Governmental Services'" and the "Conformance Class 'Application schema, Common Utility Network'" and the one between the "Conformance Class 'Application schema, Environmental Management Facilities'" and the "Conformance Class 'Application schema, Common Utility Network'" that can be removed.

![image](https://user-images.githubusercontent.com/22212406/170037480-85bad003-b11e-4e10-b6da-87f03ef27d22.png)

![image](https://user-images.githubusercontent.com/22212406/170039001-5ef1d404-5a63-4c89-bafe-725eafbd2be1.png)

**Comment by fabianospinelli** [comment]
Hi @fabiovinci . Could we have a call to better understand this issue? Thanks!

**Comment by fabianospinelli** [comment]
Resolved on branch "issues_15june"
