### ISSUE TITLE
Quick links in the "Get support" menu need to be changed

### ISSUE THREAD

**Issue by fabiovinci** [inspire-eu-validation/INSPIRE-Validator-UI#23]
Since the "Discussions" section has been added to the helpdesk-validator repository, the quick links to the issue templates need to be changed to point to the "Start a new discussion" page.

In particular:

- "Propose a new feature or improvement" should point to: https://github.com/INSPIRE-MIF/helpdesk-validator/discussions/new?category=ideas
- "Start a discussion or raise a question" should point to: https://github.com/INSPIRE-MIF/helpdesk-validator/discussions/new

The change should be made in both validator instances.

![image](https://user-images.githubusercontent.com/22212406/170730160-b31de066-51ea-4054-8c70-105e809047a7.png)

**Comment by fabianospinelli** [comment]
Links changed in every page with a ECL menu (updated in the branch "issues_15june")
