### ISSUE TITLE
Modify default parameters in metadata urls to ensure ISO compliance

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#35]
Modify default parameters in metadata urls to ensure ISO compliance considering the following issues in the helpdesk validator:

- [ INSPIRE Reference Validator - problem validate 'Metadata' for 'Data sets and data set series' #846](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/846)
- [Unable to test metadata provided as link to remote file #793](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/793)
- [Validator does not accept WMS URL #836](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/836)

**Comment by fabiovinci** [comment]
The fix for this issue was included in the release [v2023.0 - 25/01/2023](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.0).
