### ISSUE TITLE
Update captcha verification endpoint

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#45]
According to the documentation, the url endpoint for the captcha verification has changed from:
https://europa.eu/webtools/rest/captcha/verify.php
to:
https://europa.eu/webtools/rest/captcha/verify

Config file has to be updated accordingly.

It has also been reported in the INSPIRE Reference Validator helpdesk at:
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/961

**Comment by fabiovinci** [comment]
The fix for this issue was included in the release [v2023.2 - 21/06/2023](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.2).
