### ISSUE TITLE
Remove beta instance entry from the menu

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#47]
Beta instance is no longer available.
It is needed to remove the entry in the menu.

**Comment by fabiovinci** [comment]
It seems the link is still present.

**Comment by fabiovinci** [comment]
A fix for this issue was introduced in [2024.2 release](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2024.2).
