### ISSUE TITLE
Update ATS links to point to their respective master branches

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#48]
The ATS links should be revised in order to point to their respective master branches:
* View service
* WFS
* ATOM...

![imagen](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/assets/25343632/00cc83c5-73f8-4997-892c-6518789ce246)

Also master branches need to be revised in order to ensure they have the correct version of the ATSs.

**Comment by fabiovinci** [comment]
A fix for this issue was introduced in [2024.2 release](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2024.2).
