### ISSUE TITLE
Large names in the UI are not wrapped

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#49]
Large names for a test report should be wrapped and displayed in different lines.
It works fine when the test report has several words, but when there is a single long word it is not wrapped in the test report box.

Please see

![imagen](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/assets/25343632/94db32f3-3f4b-4775-87d5-0a920712f720)

**Comment by DanielMartinPerezdeLeon** [comment]
![image](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/assets/114756164/8f6dbceb-2dd8-4f01-b806-e3f28cfc64e9)

**Comment by DanielMartinPerezdeLeon** [comment]
![image](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/assets/114756164/dbebe506-89c8-444f-b9c7-bcf0b6f7c09f)


Fixed in test reports

**Comment by DanielMartinPerezdeLeon** [comment]
Added crop function in testrun similar to testreports to fix the issue on testrun:

![image](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/assets/114756164/57224a4e-8ccf-4a92-9e5b-4d9dcfb16192)
