### ISSUE TITLE
WCAG Accessibility adaptations

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#58]
WCAG compliance adaptations in the Validator UI for accesibility

**Comment by DanielMartinPerezdeLeon** [comment]
Fixed on https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/pull/51

**Comment by fabiovinci** [comment]
A fix for this issue was introduced in [2024.0.1 release](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2024.0.1).
