### ISSUE TITLE
Information version visible to the user

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#63]
According to the discussion [Information on version visible to user #1035](https://github.com/INSPIRE-MIF/helpdesk-validator/discussions/1035), the INSPIRE Reference Validator version is incorporated in the UI in a commented html string so an advanced user can consult it.

**Comment by DanielMartinPerezdeLeon** [comment]
fixed on https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/commit/0d1164c166d905576fd441089af47453e033fd57
