### ISSUE TITLE
Label for CC8 not available on the re-run page

### ISSUE THREAD

**Issue by fabiovinci** [inspire-eu-validation/INSPIRE-Validator-UI#77]
The label for the Conformance Class 8 is not available on the re-run page.

![image](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/assets/22212406/02d59853-f476-44ad-97b7-e60aaef95cc3)

**Comment by DanielMartinPerezdeLeon** [comment]
Fixed on #83
