### ISSUE TITLE
Error on re-run page for services

### ISSUE THREAD

**Issue by fabiovinci** [inspire-eu-validation/INSPIRE-Validator-UI#78]
In the re-run page related to a service test report, the section related to the resource upload should not appear since the validator should use the same service URL already used in the previous validation.

![image](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/assets/22212406/9da7d113-1591-40d1-8470-38c1add05fd3)

The only possible action on this page should be to modify the test report label and the "Start test" button should be active.

**Comment by jenriquesoriano** [comment]
This issue was present only in the Production instance, related to a bad redirection.
It has been fixed at backend level.
The UI is not affected.
