### ISSUE TITLE
Test run page-header and footer too wide

### ISSUE THREAD

**Issue by jenriquesoriano** [inspire-eu-validation/INSPIRE-Validator-UI#80]
Header and footer are too wide in the test-run page.

![310909181-57811987-c948-47ae-b1b1-e58d4c58e18e](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/assets/25343632/a6fe76ba-bb71-4554-970c-f9745e94924e)

It has been reported through the INSPIRE Reference Validator helpdesk.

See details at: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1042

**Comment by DanielMartinPerezdeLeon** [comment]
Fixed on https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/commit/6895eb4cdb4a1d34bc42e437523b8804aa5b1878
