### ISSUE TITLE
Outdated instructions to be removed

### ISSUE THREAD

**Issue by fabiovinci** [inspire-eu-validation/INSPIRE-Validator-UI#9]
The third bullet point of the "_Select the data theme(s) relevant to the data set_" menu, available for the _Dataset_ resource test, is outdated and should be removed. See the screenshot below:

![image](https://user-images.githubusercontent.com/22212406/157692967-51b8abba-c01f-4f49-b6b7-902a5e2e84e3.png)

It is present in both instances.

**Comment by fabianospinelli** [comment]
Text removed (update on branch "issues_15june")
